//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoebe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public System.Guid CargoID { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal HandlingPrice { get; set; }
        public decimal FreezePrice { get; set; }
        public decimal DisposePrice { get; set; }
        public decimal PackingPrice { get; set; }
        public decimal RentPrice { get; set; }
        public decimal OtherPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
    
        public virtual Cargo Cargo { get; set; }
    }
}
