//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoebe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupCustomer
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Code { get; set; }
        public string LegalRepresentative { get; set; }
        public string Captain { get; set; }
        public string CaptainTelephone { get; set; }
        public string Contact { get; set; }
        public string ContactTelephone { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
    }
}
