//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoebe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IceStock
    {
        public System.Guid Id { get; set; }
        public System.Guid FlowId { get; set; }
        public int IceType { get; set; }
        public int FlowCount { get; set; }
        public decimal FlowWeight { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
    
        public virtual IceFlow IceFlow { get; set; }
    }
}
