//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoebe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settlement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Settlement()
        {
            this.SettlementDetails = new HashSet<SettlementDetail>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> SumFee { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> Remission { get; set; }
        public Nullable<decimal> DueFee { get; set; }
        public Nullable<System.DateTime> SettleTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SettlementDetail> SettlementDetails { get; set; }
    }
}
