//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoebe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOutDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid StockOutId { get; set; }
        public System.Guid StoreId { get; set; }
        public int StoreCount { get; set; }
        public int Count { get; set; }
        public decimal OutWeight { get; set; }
        public decimal OutVolume { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual StockOut StockOut { get; set; }
    }
}
