//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoebe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.StockInDetails = new HashSet<StockInDetail>();
            this.StockOutDetails = new HashSet<StockOutDetail>();
            this.StockMoveDetails = new HashSet<StockMoveDetail>();
            this.StockMoveDetails1 = new HashSet<StockMoveDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CargoId { get; set; }
        public string WarehouseNumber { get; set; }
        public int TotalCount { get; set; }
        public int StoreCount { get; set; }
        public double TotalWeight { get; set; }
        public double StoreWeight { get; set; }
        public double TotalVolume { get; set; }
        public double StoreVolume { get; set; }
        public System.DateTime InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public System.DateTime MoveTime { get; set; }
        public string Specification { get; set; }
        public string OriginPlace { get; set; }
        public int ShelfLife { get; set; }
        public int Source { get; set; }
        public Nullable<int> Destination { get; set; }
        public int UserId { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockInDetail> StockInDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockOutDetail> StockOutDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMoveDetail> StockMoveDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMoveDetail> StockMoveDetails1 { get; set; }
    }
}
